name:                chapter2
version:             0.1.0.0
github:              "NewMountain/chapter2"
license:             BSD3
author:              "Christoher Nyberg"
maintainer:          "christopher.nyberg@gmail.com"
copyright:           "MIT"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/NewMountain/chapter2#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  chapter2-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - chapter2

tests:
  chapter2-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - chapter2
